// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  module.exports = function(grunt) {
    grunt.initConfig({
      pkg: grunt.file.readJSON("SFW.jquery.json"),
      banner: '// Copyright (c) <%= grunt.template.today(\'yyyy\') %>, <%= pkg.author.name %>. (MIT Licensed)\n// ==UserScript==\n// @name          <%= pkg.name %>\n// @namespace     <%= pkg.homepage %>\n// @version       <%= pkg.version %>\n// @description   <%= pkg.description %>\n// @include       <%= pkg.include %>\n// ==/UserScript==\n',
      clean: {
        files: ["dist"]
      },
      coffee: {
        compile: {
          files: {
            'js/<%= pkg.name %>.js': 'src/<%= pkg.name %>.coffee'
          }
        }
      },
      concat: {
        options: {
          banner: "<%= banner %>",
          stripBanners: true
        },
        dist: {
          src: ["libs/jquery.js", "libs/jquery.blockUI.js", "js/<%= pkg.name %>.js"],
          dest: "dist/<%= pkg.name %>.user.js"
        }
      },
      watch: {
        src: {
          files: "src/*.coffee",
          tasks: ["clean", "coffee", "concat"]
        }
      }
    });
    grunt.loadNpmTasks("grunt-contrib-clean");
    grunt.loadNpmTasks('grunt-contrib-coffee');
    grunt.loadNpmTasks("grunt-contrib-concat");
    grunt.loadNpmTasks("grunt-contrib-watch");
    return grunt.registerTask("default", ["clean", "coffee", "concat"]);
  };

}).call(this);
